# Roadmap

Tick items as they are done; keep the "Resume point" accurate so work can continue after any interruption.

## Resume point
Next: define the first entities and use cases.

## Phase 1 - Foundation
- [x] Solution generated by DotNetArch (layers, configuration, tests{{RoadmapExtras}})
- [ ] Describe the service in `docs/specs/overview.md`
- [ ] Generate the first entities (`dotnet-arch new crud --entity=...`)

## Phase 2 - Capabilities
- [ ] External capabilities as kits (`dotnet-arch new service`)
- [ ] Domain events and subscribers (`dotnet-arch new event`)

## Phase 3 - Release
- [ ] CI green, container image built, configuration examples validated
