# {{App}}

Generated by [DotNetArch](https://github.com/moein-rezaee/DotNetArch) (layout v2): Clean Architecture, ports and adapters,
vertical slices with CQRS (MediatR), unit of work and repository.

## Layout
```text
src/
  {{App}}.Domain           entities, value objects, domain events (no references)
  {{App}}.Application      ports (interfaces), features/<entities>/{Commands,Queries,Actions,Events,Dtos}, validators
  {{App}}.Infrastructure   EF Core persistence, repositories, unit of work, adapters for ports
  {{App}}.Api              controllers, configuration, composition root
```
Dependencies point inwards: `Api -> Infrastructure -> Application -> Domain`. Each layer registers its own services
(`AddApplication`, `AddInfrastructure`, `AddApi`).

## Run
```bash
cp src/{{App}}.Api/.env.example src/{{App}}.Api/.env   # secrets and run-time values
dotnet run --project src/{{App}}.Api
```

## Configuration
- `appsettings.json` - non-sensitive settings (`Database:Provider`, `Cors:AllowedOrigins`, logging).
- `.env` / environment variables - secrets and run-time values (`DATABASE_CONNECTION_STRING`). Real environment variables win over `.env`.
- Keep `.env.example` and `appsettings.example.json` in sync with the code.

## Generate more
```bash
dotnet-arch new crud --entity=Product
dotnet-arch new action --entity=Product --method=POST --action=Archive
```
