using DotNetArch.Core.Config;
using DotNetArch.Core.Hosting;
using DotNetArch.Core.NetArch;
using DotNetArch.Core.Scaffolding.Solution;

namespace DotNetArch.Core.Operations;

/// <summary>
/// Runs a generator (the old CLI/MCP "new ..." and "add ..." commands) as a registry operation. Without apply the generator runs in a throw-away copy
/// of the target folder with a runner that skips builds, restores, migrations and Docker, and the files it would create or modify become the plan;
/// with apply it runs on the real folder. In an ABP project (<c>layout: v3</c> or <c>standards: [abp]</c>) the result is then normalized by the
/// tool's own fixers (layer projects, folder tree, references, typed client, Compose) and the <c>.net-arch/</c> state is refreshed, so generated code
/// lands where the standard wants it.
/// </summary>
internal static class ScaffoldRunner
{
    public static OperationResult Run(OperationRequest request, string operation, string trackedRoot, bool skipMigrations, Action<string> action, bool normalize = true)
    {
        var apply = request.Apply;
        string? temp = null;
        var work = trackedRoot;
        if (!apply)
        {
            temp = Path.Combine(Path.GetTempPath(), "dotnet-arch-plan-" + Guid.NewGuid().ToString("N"));
            ChangeTracker.Copy(trackedRoot, temp);
            work = temp;
        }

        var buffer = new BufferedToolOutput();
        IToolOutput output = apply ? new TeeOutput(buffer, ToolHost.Output) : buffer;
        IProcessRunner runner = apply ? ToolHost.Runner : new PlanningProcessRunner(ToolHost.Runner);
        IPrompter prompter = apply ? ToolHost.Prompter : new NonInteractivePrompter();
        string? error = null;
        var exitCode = 0;
        IReadOnlyList<string> created = Array.Empty<string>();
        IReadOnlyList<string> modified = Array.Empty<string>();
        var manual = new List<string>();
        try
        {
            using var scope = ToolHost.Use(new HostContext(prompter, output, runner, skipMigrations, Planning: !apply));
            if (!SolutionTooling.EnsureDotnetSdk())
                return new OperationResult(false, string.Empty, ExitCode: 2, Error: ".NET SDK not found.");
            var changes = ChangeTracker.Begin(work);
            action(work);
            if (normalize)
                Normalization.Run(work, manual);
            (created, modified) = changes.End();
        }
        catch (Exception ex) when (ex is ArgumentException or InvalidOperationException or MissingInputException or IOException or UnauthorizedAccessException)
        {
            error = ex is MissingInputException ? $"Missing value: {ex.Message}" : ex.Message;
            exitCode = 1;
        }
        finally
        {
            if (temp != null && Directory.Exists(temp))
                TryDelete(temp);
        }

        var ok = error is null && buffer.ErrorCount == 0;
        var plan = created.Select(p => new PlannedChange(p, "create", $"generated by {operation}"))
            .Concat(modified.Select(p => new PlannedChange(p, "modify", $"updated by {operation}")))
            .ToList();
        var text = $"{operation}: {(apply ? "applied" : "plan (dry run, add --apply to write)")} - {plan.Count} change(s)\n"
                   + string.Join("\n", plan.Select(p => $"  {p.Action,-7} {p.Path}"))
                   + (buffer.ToString().Length == 0 ? string.Empty : "\n" + buffer.ToString().TrimEnd())
                   + (manual.Count == 0 ? string.Empty : "\nmanual:\n" + string.Join("\n", manual.Select(m => "  " + m)));
        return new OperationResult(ok, text, new { manual, log = buffer.ToString() }, plan, apply, ok ? 0 : Math.Max(exitCode, 1), error ?? (ok ? null : "The generator reported errors (see the log)."));
    }

    /// <summary>Loads dotnet-arch.yml of a (work copy of a) solution and points its path at that folder.</summary>
    public static SolutionConfig LoadConfig(string work, string original)
    {
        var config = ConfigManager.Load(work)
            ?? throw new InvalidOperationException($"Solution configuration (dotnet-arch.yml) not found in '{original}'. Run new_solution first.");
        config.SolutionPath = work;
        return config;
    }

    private static void TryDelete(string path)
    {
        try
        {
            Directory.Delete(path, recursive: true);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }

    private sealed class TeeOutput(IToolOutput first, IToolOutput second) : IToolOutput
    {
        public void Section(string emoji, string title, string? description = null)
        {
            first.Section(emoji, title, description);
            second.Section(emoji, title, description);
        }

        public void SubStep(bool success, string message)
        {
            first.SubStep(success, message);
            second.SubStep(success, message);
        }

        public void Blank()
        {
            first.Blank();
            second.Blank();
        }
    }
}
