<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool> <!-- Convert To Global Tool -->
    <ToolCommandName>dotnet-arch</ToolCommandName> <!-- For Execute CLI -->
    <Nullable>enable</Nullable>
    <Authors>Moein Rezaee</Authors>
    <Description>A CLI tool for creating Clean Architecture solutions.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>DotNetArch</PackageId>
    <Version>1.2.0</Version>
    <PackageTags>dotnet;cli;clean-architecture;scaffold;dotnetarch</PackageTags> 
    <RepositoryUrl>https://github.com/moein-rezaee/DotNetArch.git</RepositoryUrl>
    <PackageIcon>assets/icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <!-- Debug: اجرای ساده با یک فریم‌ورک پیش‌فرض -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <!-- Release: چندفریم‌ورکی برای پکیج ابزار -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="assets/icon.png" Pack="true" PackagePath="assets/" />
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>



</Project>
