# corevia:managed service-cicd.split sha256=18c6af1e04c32635c693707b2a7daf6af00cc2f83051a703b6afde1fbe867358
#!/usr/bin/env ruby
# frozen_string_literal: true
# Generated by corevia-run (service-cicd.split). Do not hand-edit -- edit the service_cicd values
# file and re-apply. Two subcommands, run from the `validate` CI stage before `build`:
#   documentation -- README/docs bilingual pairing, placeholder text, required sections, broken relative links.
#   version       -- the main project's csproj <Version> must increase when its own source changed.

require "json"
require "fileutils"
require "open3"
require "pathname"
require "rexml/document"

ROOT = File.expand_path("../..", __dir__)
MODE = ARGV.fetch(0)
PROJECT_HINT = "IdentityService.Api"

def write_report(name, data)
  path = File.join(ROOT, ".work", "reports", name)
  FileUtils.mkdir_p(File.dirname(path))
  File.write(path, JSON.pretty_generate(data))
  puts JSON.pretty_generate(data)
  exit(data[:ok] ? 0 : 1)
end

def documentation_validation
  errors = []
  files = ([File.join(ROOT, "README.md"), File.join(ROOT, "README.fa.md")] +
           Dir.glob(File.join(ROOT, "docs", "**", "*.md"))).uniq.sort.select { |p| File.file?(p) }
  placeholders = [
    /Brief purpose of this documentation section/i,
    /Brief explanation\.?/i,
    /هدف اصلی و کاربرد این بخش یا ماژول/,
    /محدوده و بازه تاثیر این بخش/,
    /محتوای بخش/,
    /توضیح مختصر\.?/
  ]
  required_sections = {
    "purpose" => /^(Purpose|هدف|مقصد)$/i,
    "scope" => /^(Scope|محدوده|دامنه)$/i,
    "prerequisites" => /^(Prerequisites|پیش[‌-]?نیاز(?:ها)?)$/i,
    "configuration" => /^(Configuration|پیکربندی)$/i,
    "run-usage" => /^(Run(?:\s*\/\s*Usage)?|اجرا(?:\s+و\s+استفاده)?)$/i,
    "validation" => /^(Validation(?:\s*\/\s*Verification)?|اعتبارسنجی|تایید|تصدیق)$/i,
    "troubleshooting" => /^(Troubleshooting|رفع اشکال|عیب[‌-]?یابی)$/i,
    "change-log" => /^(Change Log|تغییرات|سیاق تغییرات|تاریخچه تغییرات)$/i,
    "ownership" => /^(Ownership|مالکیت)$/i
  }
  files.each do |path|
    rel = Pathname.new(path).relative_path_from(Pathname.new(ROOT)).to_s
    next if File.basename(path).start_with?("AGENTS")

    content = File.read(path, encoding: "UTF-8")
    pair = path.end_with?(".fa.md") ? path.sub(/\.fa\.md\z/, ".md") : path.sub(/\.md\z/, ".fa.md")
    errors << "[PAIR] #{rel}" unless File.file?(pair)
    if File.file?(pair)
      marker = path.end_with?(".fa.md") ? /\[English\]\(/ : /\[فارسی\]\(/
      errors << "[LANGUAGE_LINK] #{rel}" unless content.match?(marker)
    end
    placeholders.each { |pattern| errors << "[PLACEHOLDER] #{rel}" if content.match?(pattern) }
    if File.basename(path).match?(/\AREADME(?:\.fa)?\.md\z/)
      headings = content.scan(/^##\s+(.+?)\s*$/).flatten.map(&:strip)
      required_sections.each { |name, pattern| errors << "[SECTION:#{name}] #{rel}" unless headings.any? { |h| h.match?(pattern) } }
    end
    content.scan(/\[[^\]]+\]\(([^)]+)\)/).flatten.each do |link|
      next if link.empty? || link.start_with?("http://", "https://", "mailto:", "#", "<")

      target = link.split("#", 2).first
      next if target.empty? || target.include?("<") || target.match?(/\.(png|jpe?g|gif|svg|webp|ico)\z/i)

      errors << "[LINK] #{rel}: #{link}" unless File.exist?(File.expand_path(target.gsub("%20", " "), File.dirname(path)))
    end
  end
  write_report("documentation.json", ok: errors.empty?, mode: "documentation", scanned_files: files.length, errors: errors.uniq)
end

def project_metadata(xml)
  doc = REXML::Document.new(xml)
  get = ->(name) { REXML::XPath.first(doc, "//#{name}")&.text.to_s.strip }
  { version: get.call("Version") }
end

def main_project
  return nil if PROJECT_HINT.to_s.empty?

  candidates = Dir.glob(File.join(ROOT, "**", "*.csproj")).reject { |p| p.include?("/bin/") || p.include?("/obj/") }
  candidates.find { |p| File.basename(File.dirname(p)) == PROJECT_HINT } ||
    candidates.find { |p| File.basename(p, ".csproj") == PROJECT_HINT }
end

def version_validation
  project = main_project
  if project.nil?
    write_report("version.json", ok: true, mode: "version", note: "no main project configured/found for this repo; skipped")
    return
  end
  base = ENV.fetch("COREVIA_VERSION_BASE_REF")
  rel = Pathname.new(project).relative_path_from(Pathname.new(ROOT)).to_s
  current = project_metadata(File.read(project))
  semver = /\A(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z.-]+))?\z/
  parts = lambda do |value|
    m = value.to_s.match(semver)
    m ? [m[1].to_i, m[2].to_i, m[3].to_i] : nil
  end
  errors = []
  errors << "#{rel}: missing or invalid <Version>" unless parts.call(current[:version])
  diff, diff_error, diff_status = Open3.capture3("git", "diff", "--name-only", base, "--", chdir: ROOT)
  errors << "cannot diff against #{base}: #{diff_error.strip}" unless diff_status.success?
  changed = diff.lines.map(&:strip).reject(&:empty?)
  project_dir = File.dirname(rel)
  relevant_change = changed.any? do |p|
    (p == rel || p.start_with?("#{project_dir}/")) && !p.include?("/docs/") && !File.basename(p).start_with?("README")
  end
  old_xml, _old_error, old_status = Open3.capture3("git", "show", "#{base}:#{rel}", chdir: ROOT)
  if relevant_change && old_status.success?
    previous = project_metadata(old_xml)
    if parts.call(current[:version]) && parts.call(previous[:version]) &&
       (parts.call(current[:version]) <=> parts.call(previous[:version])) <= 0
      errors << "#{rel}: source changed but <Version> did not increase (#{previous[:version]} -> #{current[:version]})"
    end
  end
  write_report("version.json", ok: errors.empty?, mode: "version", project: rel, current_version: current[:version], errors: errors)
end

case MODE
when "documentation" then documentation_validation
when "version" then version_validation
else
  warn "unknown mode: #{MODE}"
  exit 1
end
