# AGENTS - {{App}}

Rules for people and agents changing this repository. Generated by DotNetArch (layout v2); adapt them, do not drop them.

## Before you change anything
1. Read `docs/specs/overview.md`, `contracts.md`, `acceptance.md` and `docs/roadmap.md`.
2. Machine-readable specs live in `docs/specs/openspec.yaml` and `docs/specs/testspec.yaml`.

## Spec Rule
- A behaviour, API or configuration change updates `docs/specs/*` (and the `.fa.md` pairs) in the same change.
- New use case = contract entry in `contracts.md` and an acceptance line.

## Architecture Rule
- Dependencies point inwards: `Api/Mcp -> Infrastructure -> Application -> Domain`. Domain references nothing; Application never references Infrastructure, a host or a kit Core/Provider.
- Ports (interfaces) live in Application; adapters live in Infrastructure. Application sees a kit's `Abstractions` only; kit `Core` and providers are referenced by the composition root (Api/Mcp).
- Each layer registers its own services through its own extension (`AddApplication`, `AddInfrastructure`, `AddApi`/`AddMcpHost`); hosts only call them. A layer references only the packages it uses.
- One entity = one folder `Features/<Plural>/`: `Commands/<UseCase>/`, `Queries/<UseCase>/`, `Actions/<UseCase>/`, `Events/`, `Dtos/`, `Services/`. Controllers and MCP tools follow the same grouping.
- CQRS with MediatR; validation in FluentValidation validators; state changes only through domain methods (private setters).
- Repositories return materialised results through async methods; never expose `IQueryable`. No sync-over-async, no `Console` diagnostics, no hard-coded secrets, no permissive CORS defaults.

## Configuration Rule
- Non-sensitive settings: `appsettings.json` (PascalCase, colon keys). Secrets and run-time values: environment / `.env` (UPPER_CASE with single underscores). Both are loaded by `AddAppConfiguration()` before any options binding.
- Any key you add, rename or remove updates `.env.example` and `appsettings.example.json` and, for secrets, `ConfigurationContract`. The tests tagged `Category=Configuration` (and `scripts/validate-examples.sh`) enforce it.
- Never commit `.env` or real secrets; examples hold placeholders only.

## Kit Rule
- External capabilities (cache, message broker, media storage, ...) are kits under `kits/<Area>`: `Abstractions` + `Core` + `Providers.*`, independently versioned. Generate with `dotnet-arch new service` (no business logic) or `new kit`.
- Never reference a product SDK (Redis, RabbitMQ, S3, ...) from Domain, Application or a feature; add a provider package to the kit instead.

## Testing Rule
- Every layer has a test project under `tests/`. New use cases ship with tests; `dotnet test` must pass before merging.
- Provider/kit tests use stubs; do not claim live verification against a real server unless it was run.

## Generating code
```bash
dotnet-arch new crud --entity=Product                 # CRUD slice + tests (+ MCP tools when the MCP host exists)
dotnet-arch new action --entity=Product --action=Archive --method=POST
dotnet-arch new event --entity=Product --name=Created
dotnet-arch new service                               # business service or kit
dotnet-arch add mcp | ci add | docker add | git setup
```

## Documentation Governance Rule
- Keep `.md` + `.fa.md` pairs synchronised (`scripts/check-docs.sh`). Update `docs/roadmap.md` in the same change as the work.
