using DotNetArch.Core.Scaffolding.Kits;
using DotNetArch.Core.Templating;

namespace DotNetArch.Core.Scaffolding.V2;

/// <summary>
/// <c>new service</c> for layout v2. A service with business logic becomes an Application service; a service without
/// business logic (an external capability) becomes a Kit (Abstractions + Core + providers), wired into the composition root.
/// </summary>
public static class ServiceV2Generator
{
    public static readonly string[] Lifetimes = { "Scoped", "Transient", "Singleton" };

    private const string OtherArea = "Other (new area)";

    /// <summary>Interactive entry point used by the CLI when no explicit options were given.</summary>
    public static bool Run(SolutionConfig config)
    {
        if (ToolHost.AskYesNo("Does this service contain business logic?", true))
        {
            var entity = ToolHost.Ask("Enter entity name (optional, the service lives inside that entity's feature folder)", string.Empty);
            var name = ToolHost.Ask("Enter service name");
            var lifetime = ToolHost.AskOption("Select lifetime", Lifetimes);
            return GenerateInternal(config, string.IsNullOrWhiteSpace(entity) ? null : entity, name, lifetime);
        }

        var choices = KitRecipes.All.Select(recipe => recipe.Area).Append(OtherArea).ToArray();
        var area = ToolHost.AskOption("Select the external capability (a kit is generated for it)", choices);
        if (area == OtherArea)
            area = ToolHost.Ask("Enter the capability name (for example Search, Payment)");

        var recipe = KitRecipes.Find(area);
        var defaultProviders = recipe is null ? "Default" : string.Join(",", recipe.Providers.Select(provider => provider.Name));
        var providers = ToolHost.Ask("Providers (comma separated)", defaultProviders);
        var withTests = ToolHost.AskYesNo("Generate kit tests?", false);

        return GenerateKit(config, area, providers.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries), withTests);
    }

    public static bool GenerateKit(SolutionConfig config, string area, IReadOnlyList<string> providers, bool withTests)
    {
        area = KitGenerator.NormalizeArea(area);
        var existing = Path.Combine(config.SolutionPath, "kits", area, KitGenerator.MetadataFile);
        if (File.Exists(existing))
        {
            ToolHost.Info($"Kit {area} already exists; wiring it into the solution.");
            return KitWiring.WireFromDisk(config, area);
        }

        var prefix = string.IsNullOrWhiteSpace(config.KitPrefix) ? config.SolutionName : config.KitPrefix;
        var major = PackageVersionResolver.ResolveTargetMajor(config.TargetFramework);
        var info = KitGenerator.Generate(new KitRequest(config.SolutionPath, area, providers, prefix, major, withTests));
        return KitWiring.Wire(config, info);
    }

    public static bool GenerateInternal(SolutionConfig config, string? entity, string name, string lifetime)
    {
        if (!config.IsV2)
            throw new InvalidOperationException("Internal services for this layout are generated by the legacy flow.");

        Identifier.RequireIfPresent(entity, "entity name");
        name = Identifier.RequireIdentifier(Identifier.Sanitize(name), "service name");
        name = char.ToUpperInvariant(name[0]) + name[1..];
        lifetime = Lifetimes.FirstOrDefault(l => l.Equals(lifetime, StringComparison.OrdinalIgnoreCase))
            ?? throw new ArgumentException($"Lifetime must be one of: {string.Join(", ", Lifetimes)}.");

        var app = config.SolutionName;
        string folder;
        string @namespace;
        if (string.IsNullOrWhiteSpace(entity))
        {
            folder = $"src/{app}.Application/Common/Services";
            @namespace = $"{app}.Application.Common.Services";
        }
        else
        {
            if (!EntityGeneration.EntityExists(config, entity))
            {
                ToolHost.Error($"Entity '{entity}' does not exist.", "Create it first with 'new crud', or omit the entity for a common service.");
                return false;
            }

            var plural = Naming.Pluralize(entity);
            folder = $"src/{app}.Application/Features/{plural}/Services";
            @namespace = $"{app}.Application.Features.{plural}.Services";
        }

        var tokens = new Dictionary<string, string> { ["Namespace"] = @namespace, ["ServiceName"] = name };
        var writer = new FileWriter(config.SolutionPath);
        if (!writer.Write($"{folder}/{name}.cs", TemplateRenderer.RenderTemplate("V2/service/Service.cs.tpl", tokens)))
        {
            ToolHost.Error($"Service {name} already exists.");
            return false;
        }

        RegisterService(config, @namespace, name, lifetime);
        ToolHost.Success($"{name} service generated.", $"registered as {lifetime} in AddApplication()");
        return true;
    }

    private static void RegisterService(SolutionConfig config, string @namespace, string name, string lifetime)
    {
        var path = Path.Combine(config.SolutionPath, config.ProjectDirectory($"{config.SolutionName}.Application"), "DependencyInjection.cs");
        var text = File.ReadAllText(path);
        var registration = $"        services.Add{lifetime}<I{name}, {name}>();\n";
        var usingLine = $"using {@namespace};\n";

        if (!text.Contains("// <dotnet-arch:services>", StringComparison.Ordinal))
        {
            ToolHost.Error("Could not register the service automatically.", $"Add 'services.Add{lifetime}<I{name}, {name}>();' to AddApplication().");
            return;
        }

        if (!text.Contains(usingLine, StringComparison.Ordinal))
            text = InsertAtMarkerLine(text, "// <dotnet-arch:service-usings>", usingLine);
        if (!text.Contains($"<I{name}, {name}>", StringComparison.Ordinal))
            text = InsertAtMarkerLine(text, "// <dotnet-arch:services>", registration);
        File.WriteAllText(path, text, new System.Text.UTF8Encoding(false));
    }

    private static string InsertAtMarkerLine(string text, string marker, string insertion)
    {
        var index = text.IndexOf(marker, StringComparison.Ordinal);
        var lineStart = text.LastIndexOf('\n', index) + 1;
        return text.Insert(lineStart, insertion);
    }
}
