# {{App}} - overview

{{App}} is a microservice generated by DotNetArch (layout v2).

## Purpose
TODO: describe in two sentences what this service owns and who calls it.

## Architecture
Clean Architecture with ports and adapters, vertical slices and CQRS (MediatR), unit of work and repository.
`Api (and Mcp) -> Infrastructure -> Application -> Domain`; every layer registers its own services; kits provide external capabilities.

## Runtime
- Database: {{Provider}} (EF Core). Configuration: appsettings (non-sensitive) + `.env`/environment (secrets).
- Entry points: HTTP API (`src/{{App}}.Api`){{McpLine}}.

## Out of scope
TODO.
